### PR TITLE
Refactor the directory of subscriptions for a better file organization.

### PR DESCRIPTION
**Pull request by rexwangcc**
### Purpose

- https://broadinstitute.atlassian.net/jira/software/projects/GH/boards/530?selectedIssue=GH-319

### Changes

- Extract all subcription-related files from the `scripts` dir to a new dir called `subscription`

### Review Instructions

- No instructions.

### CODE REVIEW

**Review by rhiananthony — APPROVED** [review]
FWIW LGTM :)

**Comment by samanehsan** [comment]
I think `config-template.sh` belongs in the `subscriptions` folder. Since scripts like `subscription-create.sh` are loading variables from a config file it is useful to have the template file in that directory. After that change (and the change to the snyk requirements) I think this is good to merge :octocat:

**Comment by rexwangcc** [comment]
@samanehsan Good catch! I will move that to the new place. Thanks!

**Comment by rexwangcc** [comment]
@rhiananthony It seems the snyk integration needs to be fixed after this PR gets merged.

**Pull request merged**
