### PR TITLE
Make HCA schema_url configurable

### PR DESCRIPTION
**Pull request by samanehsan**
Now that there are different environments for the HCA metadata schemas, make the url configurable in Lira. This parameter will get included in the pipeline inputs JSON file that gets passed to Cromwell.

Note: The environment to use for the metadata schema url will match the Lira environment: e.g. integration Lira will use `http://schema.integration.data.humancellatlas.org/` and staging Lira will use `http://schema.staging.data.humancellatlas.org/`. 

Please ensure the following when opening a PR:
- [ ] Added or updated tests
- [ ] Updated documentation
- [ ] Applied style guidelines
- [ ] Considered generalizability beyond our own use case

### CODE REVIEW

**Comment by samanehsan** [comment]
retest this please

**Comment by samanehsan** [comment]
retest this please

**Comment by samanehsan** [comment]
retest this please

**Comment by samanehsan** [comment]
retest this please

**Comment by samanehsan** [comment]
retest this please

**Review by rexwangcc — APPROVED** [review]
👍

**Pull request merged**
