### PR TITLE
Dynamically add env-specific urls to lira inputs

### PR DESCRIPTION
**Pull request by samanehsan**
Add the `dss_url` and `submit_url` to the workflow inputs based on the current lira environment, instead of always using staging.

### CODE REVIEW

**Review by dshiga — APPROVED** [review]

**Comment by samanehsan** [comment]
retest this please

**Comment by samanehsan** [comment]
retest this please

**Comment by samanehsan** [comment]
retest this please

**Comment by samanehsan** [comment]
retest this please

**Pull request merged**
